### ISSUE TITLE
Can't take photo

### ISSUE THREAD

**Issue by pamobo0609** [filestack/filestack-android#156]
Hi there! I'm trying to implement this on a project I'm working on, but I keep getting a NPE when trying to open the camera inside de FsActivity. I don't know why is this happening if the file_paths is defined and declared inside the Manifest...
The file_paths file is declared as follows:
```
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="external_files"
        path="." />

</paths>
```
And the manifest is looking like this:
```        
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
```

**Comment by shawnmaten** [comment]
We expect external paths *named* "pictures" and "movies" exactly. Their corresponding real file system paths don't have be inside internal app storage, as in our example, but I think the sensible locations are that or the public camera directories.

Here's the example from the README (replace package domain):

```
<external-path name="pictures" path="Android/data/com.filestack.android.demo/files/Pictures" /><external-path name="movies" path="Android/data/com.filestack.android.demo/files/Movies" />
```

**Comment by pamobo0609** [comment]
Thanks for the answer mate.
I just changed the file_paths to 
```
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="pictures"
        path="Android/data/com.magorasystems.tutormatchingservice/files/Pictures" />
    <external-path
        name="movies"
        path="Android/data/com.magorasystems.tutormatchingservice/files/Movies" />

</paths>
```

I even tried to set the root path for both pictures and movies (.) but still seeing this error: 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
```

**Comment by shawnmaten** [comment]
Where do you have the `file_paths.xml` file saved? The path should be:
[path to your Android Studio module]/src/main/res/xml/file_paths.xml

**Comment by pamobo0609** [comment]
The path is exactly that.
<img width="352" alt="screen shot 2018-02-01 at 15 30 14" src="https://user-images.githubusercontent.com/5050412/35704351-d3e56a72-0764-11e8-8bbf-5c9483d1e082.png">

**Comment by shawnmaten** [comment]
The provider should have an authority of [PACKAGE NAME] + "fileprovider". I'm assuming your variable substitution is working but I'm not used to seeing that in a manifest.

`android:authorities="${applicationId}.provider"`
should be
`android:authorities="${applicationId}.fileprovider"`

We can probably make that more clear in the README.

**Comment by pamobo0609** [comment]
Hi man! I was finishing some other stuff but now I can pay full attention to this.
I made the changes as you suggested, but now I have a different crash:

```
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.magorasystems.tutormatchingservice.dev/files/Pictures/JPEG_20180207_144445_6481568081761840444.jpg
                                                                                              at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:719)
                                                                                              at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:404)
                                                                                              at com.filestack.android.internal.Util.getUriForInternalMedia(Util.java:201)
                                                                                              at com.filestack.android.internal.CameraFragment.createCameraIntent(CameraFragment.java:108)
                                                                                              at com.filestack.android.internal.CameraFragment.onClick(CameraFragment.java:52)
                                                                                              at android.view.View.performClick(View.java:6256)
                                                                                              at android.view.View$PerformClick.run(View.java:24697)
                                                                                              at android.os.Handler.handleCallback(Handler.java:789)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
Don't know why is this happening. It doesn't even ask me for camera or storage permissions.
Any thoughts?
Thanks

**Comment by pamobo0609** [comment]
Thanks for all the help man. Now it's working.

**Comment by shawnmaten** [comment]
Glad to hear it’s working!
